Quixk Fix: Small issues in profiles
zowe/vscode-extension-for-zowe pull request #1100
Opened 2020-12-08 17:42 UTC by jellypuno

## Proposed changes

These are small changes and are not high priority.

Changes Include:
- Remove the word Optional in Username and Password
- Display the error message when Profile Inactive is encountered
- Handle the additional fields when creating and editing a profile when the user cancelled it.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2020-12-09 18:14 UTC, JillieBeanSim reviewed
@jellypuno this is looking good but I did get this error when updating a profile and going all the way through the update process.  It fully updated the profile, yaml included but got the error on top of successful message
![image](https://user-images.githubusercontent.com/49491949/101669877-80406380-3a20-11eb-8d7d-5e3530f06fa0.png)

2020-12-09 18:23 UTC, jellypuno commented
> @jellypuno this is looking good but I did get this error when updating a profile and going all the way through the update process. It fully updated the profile, yaml included but got the error on top of successful message
> ![image](https://user-images.githubusercontent.com/49491949/101669877-80406380-3a20-11eb-8d7d-5e3530f06fa0.png)

Thank you for testing @JillieBeanSim . I will take a look at this tomorrow.

2020-12-16 14:29 UTC, zFernand0 reviewed
Added a couple of comments 😋

2020-12-16 14:29 UTC, zFernand0 commented on packages/zowe-explorer/src/Profiles.ts
>                                  updSchemaValues[value] = Number(updValue);
If input is an empty string (i.e. the user hit enter), `Number("") === 0`
This results in the profile still being saved with `responseTimeout: 0`.

We could check for `updValue !== "" && !Number.isNaN(Number(updValue)` but that leads to another problem. (see next comment)

This comments applies to both Creating a new Connection (`createNewConnection`) and Editing a session (`editSession`)

2020-12-16 14:29 UTC, zFernand0 commented on packages/zowe-explorer/src/Profiles.ts
> +                                        }
If the user didn't enter a value for a numeric property, and the schema contains a null value, we should still create the profile without this property.

For comparison, here are the schema definitions encoding and responseTimeout
```
{
  "name": "encoding",
  "aliases": ["ec"], 
  "description": "The encoding for download and upload of z/OS data set and USS files. The default encoding if not specified is 1047.",
  "type":"number"
}
```

```
{
  "name": "responseTimeout",
  "aliases": ["rto"],
  "description": "The maximum amount of time in seconds the z/OSMF Files TSO servlet should run before returning a response. Any request exceeding this amount of time will be terminated and return an error. Allowed values: 5 - 600",
  "type": "number",
  "defaultValue": null,
  "numericValueRange": [5,600]
}
```

2020-12-17 10:04 UTC, jellypuno commented
@zFernand0 Just a clarification, are you saying that if the user enters a blank in the property (e.g. responseTimeOut) we should create the profile with a blank value instead of zero? or are saying that we should not add the property into the profile?

2020-12-17 11:19 UTC, jellypuno commented
Since this is a generic checking of number, If I try to allow the creation of profile that is equal to null, we are having this error.

![image](https://user-images.githubusercontent.com/45042840/102481193-ae95f280-4061-11eb-83ff-4a0c4da5f54a.png)

In my opinion, if it is defined as a number, the default number should not be null. I opened an issue for that: https://github.com/zowe/zowe-cli/issues/871

2020-12-17 12:03 UTC, zFernand0 commented
> are you saying that if the user enters a blank in the property (e.g. responseTimeOut) we should create the profile with a blank value instead of zero? or are saying that we should not add the property into the profile?

The latter. We should not store properties that: 
  - Do not have a default value set by the schema
  - The user didn't specify a value

2020-12-17 12:34 UTC, jellypuno commented
@zFernand0 I plan to add this in the future. The goal of this PR is just to handle those additional fields. Because right now, if I cancelled the creation / editing with those additional fields it will display an error and not "Operation Cancelled"

2021-01-05 13:51 UTC, katelynienaber commented
@jellypuno 2 things:

1: Does this fix [this issue (#1065)](https://github.com/zowe/vscode-extension-for-zowe/issues/1065)?
2: I think it might be better to store empty strings than totally remove the fields. The reason is that Imperative is using `deepmerge` to merge old and new profiles when editing them, and if the new profile doesn't have all the same fields as the old one, `deepmerge` retains the old fields (and their values) when merging. See [this PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1120) for some affected fields...maybe there is a better way to deal with this, I am not sure.

2021-01-05 14:13 UTC, jellypuno commented
> @jellypuno 2 things:
> 
> 1: Does this fix [this issue (#1065)](https://github.com/zowe/vscode-extension-for-zowe/issues/1065)?
> 2: I think it might be better to store empty strings than totally remove the fields. The reason is that Imperative is using `deepmerge` library to merge a profile's old and new values when updating the profile. If the new profile doesn't have all the same fields as the old one, `deepmerge` retains the old fields (and their values) when merging. See [this PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1120) for some fields affected by `deepmerge`. Maybe there is a better way to deal with this than storing empty strings...what do you think?

I don't think I'm removing it. I'm storing it as spaces or default value. The handling that I added is that if you cancelled the Profile Creation on those new fields the error message is better. But maybe I need to double check

2021-01-05 16:23 UTC, katelynienaber commented
> > @jellypuno 2 things:
> > 1: Does this fix [this issue (#1065)](https://github.com/zowe/vscode-extension-for-zowe/issues/1065)?
> > 2: I think it might be better to store empty strings than totally remove the fields. The reason is that Imperative is using `deepmerge` library to merge a profile's old and new values when updating the profile. If the new profile doesn't have all the same fields as the old one, `deepmerge` retains the old fields (and their values) when merging. See [this PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1120) for some fields affected by `deepmerge`. Maybe there is a better way to deal with this than storing empty strings...what do you think?
> 
> I don't think I'm removing it. I'm storing it as spaces or default value. The handling that I added is that if you cancelled the Profile Creation on those new fields the error message is better. But maybe I need to double check

I was referring to your conversation with @zFernand0 ...so I will tag him in that comment :)

2021-01-08 14:16 UTC, katelynienaber requested changes
Looks good and works as expected. The basePath is still not updated when the profile is edited...but I think that's out of scope and is already fixed in [another PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1120).

IMHO though we should maybe leave the `optional` placeholder when creating/editing a profile, but remove it when prompted for username/password.

2021-01-08 14:26 UTC, jellypuno commented
> Looks good and works as expected. The basePath is still not updated when the profile is edited...but I think that's out of scope and is already fixed in [another PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1120).
> 
> IMHO though we should maybe leave the `optional` placeholder when creating/editing a profile, but remove it when prompted for username/password.

I removed the optional word because it is used by ssoLogin and it is not supposed to optional.

2021-01-08 14:28 UTC, katelynienaber commented
> > Looks good and works as expected. The basePath is still not updated when the profile is edited...but I think that's out of scope and is already fixed in [another PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1120).
> > IMHO though we should maybe leave the `optional` placeholder when creating/editing a profile, but remove it when prompted for username/password.
> 
> I removed the optional word because it is used by ssoLogin and it is not supposed to optional. It didn't make sense to create another text just for ssoLogin so I just removed the optional because we intend to remove the Optional Credentials in the future

Ah okay, SO GLAD we will remove optional credentials! I didn't know that was the plan so I will approve now.

2021-01-08 14:28 UTC, katelynienaber approved these changes
LGTM!

2021-01-08 20:31 UTC, JillieBeanSim reviewed
Hey @jellypuno when I was creating and editing a zosmf profile, I hit the escape at the encoding value.  I was expecting the `operation cancelled` message to pop up then but instead it went to the next textbox for response timeout then I clicked escape again to get the `operation cancelled` message.
Is this expected, as I was not expecting to get prompted with another textbox after hitting escape the first time?

2021-01-11 10:04 UTC, jellypuno commented
> Hey @jellypuno when I was creating and editing a zosmf profile, I hit the escape at the encoding value. I was expecting the `operation cancelled` message to pop up then but instead it went to the next textbox for response timeout then I clicked escape again to get the `operation cancelled` message.
> Is this expected, as I was not expecting to get prompted with another textbox after hitting escape the first time?

Did you get the latest commit? It is not happening for me.

![operCancel](https://user-images.githubusercontent.com/45042840/104167542-ca8c7a00-53fc-11eb-8424-96c33a55a57e.gif)

2021-01-12 15:11 UTC, JillieBeanSim submitted a review, later dismissed
@jellypuno I must have been missing a commit.  This LGTM, functionality is working as expected but I do get a few failing integration tests that deal with creating a profile now that I didn't get on Master branch. 

![image](https://user-images.githubusercontent.com/49491949/104331409-07b84100-54bd-11eb-8205-8e9f5f97d9dc.png)

2021-01-14 12:56 UTC, jellypuno commented
@JillieBeanSim I fixed the integration test. Thank you for testing and reviewing this PR.

2021-01-14 13:20 UTC, katelynienaber approved these changes
LGTM :)

2021-01-14 13:41 UTC, JillieBeanSim approved these changes
This LGTM, all expected tests and checks are passing and functionality works great! Thanks for all of your work on this @jellypuno, fixing these small issues make a huge positive impact for users.

2021-01-14 15:03 UTC, merged