Issue #989: Editing Base Path on a ZE Connection Profile Doesn't Save it
zowe/vscode-extension-for-zowe pull request #1120
Opened 2021-01-04 17:28 UTC by katelynienaber

## Proposed changes

Two (small, deceptively related) bugs fixed here:
1. If a profile YAML doesn't contain a base path, it can't be added via the VSCode extension (YAML isn't updated)
2. If a base path exists in the YAML, it can't be removed via the VSCode extension

Summary of fixes:
1. First issue was caused by passing new profile values to Imperative as CLI arguments, without changing the keys to match the expected CLI arguments. So ex. key `basePath` has now been changed to `base-path` when it is passed to Imperative. This bug also affected key `rejectUnauthorized`, which has been fixed in the same way.
2. Imperative's use of `deepmerge` caused the second issue. Now, instead of removing the base path property entirely, I give it an empty string value. And `deepmerge` replaces the old basePath value with the new empty string, instead of trying to retain all properties of both objects and (oops!) copying the old basePath into the new merged object.

Linked issue: [#989](https://github.com/zowe/vscode-extension-for-zowe/issues/989)

## Release Notes

Milestone: 1.12
Changelog: Fixed errors retaining `basePath` & `rejectUnauthorized` changes after editing in Zowe Explorer

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

2021-01-08 19:48 UTC, JillieBeanSim commented
Hey @katelynienaber I was testing this PR, while creating a profile I still get `""` for optional values left blank along with the `0` value for encoding and response timeout that where left blank/entered passed.  
![image](https://user-images.githubusercontent.com/49491949/104057515-49e13a00-51c0-11eb-9021-ca5f2adf99df.png)

Then I edited the same profile leaving those same values blank and still got `0` in the yaml for them.
![image](https://user-images.githubusercontent.com/49491949/104057578-641b1800-51c0-11eb-8dde-ea627683ba0f.png)

2021-01-08 19:52 UTC, JillieBeanSim requested changes
see comment above for issues I ran into.

the changes requested are:
Should we use this same way of thinking during create?
Also, would like to see the default value for encoding used or leave it out of the yaml 
Finally, shouldn't it leave response timeout out of the yaml if value = 0?

2021-01-08 23:35 UTC, katelynienaber commented
> see comment above for issues I ran into.
> 
> the changes requested are:
> Should we use this same way of thinking during create?
> Also, would like to see the default value for encoding used or leave it out of the yaml
> Finally, shouldn't it leave response timeout out of the yaml if value = 0?

Hey @JillieBeanSim, give it a shot now.

**Should we use this same way of thinking during create?**
I think so. Create is kind of hacky right now because the `CliProfileManager.save` function does some validation, and won't let you pass in non-string values for user & password. So I'm calling our `updateProfile` function on newly-created profiles, just after the profile manager is refreshed, to remove any blank fields.

**Also, would like to see the default value for encoding used or leave it out of the yaml**
This one should be fixed. I rearranged the conditions in that loop I added.

**Finally, shouldn't it leave response timeout out of the yaml if value = 0?**
This should also be good now.

2021-01-11 09:43 UTC, jellypuno commented
> Should we use this same way of thinking during create?
> I think so (and now Create should work in the new way, not storing empty values). Create is kind of hacky right now because the CliProfileManager.save function does some validation, and won't let you pass in non-string values for user & password. So I'm calling our updateProfile function on newly-created profiles, just after the profile manager is refreshed, to remove any blank fields.

@katelynienaber Let's think of another way and not implement a hack. We can check zowe/cli code as to how they implmented this.

@JillieBeanSim When you say "same way of thinking during create", Are you thinking of re-factoring that process? Code-wise or UX-wise or both? If yes, do you a design that we can look into?

2021-01-11 12:07 UTC, katelynienaber commented
@JillieBeanSim Ok, now we have a not-hacky solution :) @jellypuno pointed out that [this option](https://github.com/zowe/imperative/blob/741f24f7246028879317dbd9590b91d7efbdef39/packages/cmd/__tests__/profiles/CliProfileManager.test.ts#L280) could allow passing optional parameters, and it works (at least for me)

Please check again when you have time ^^"

2021-01-11 13:06 UTC, JillieBeanSim commented
> 
> @JillieBeanSim When you say "same way of thinking during create", Are you thinking of re-factoring that process? Code-wise or UX-wise or both? If yes, do you a design that we can look into?

@jellypuno I was only thinking of the way it was saved to the yaml, ie. no empty strings and `0` values, not a UI change.

Thanks for looking into my questions and concerns @katelynienaber & @jellypuno I will retest the PR today.

2021-01-12 15:34 UTC, JillieBeanSim commented
@katelynienaber the functionality works well now and as expected for create and update of profiles without optional user/pass and for the empty encoding and response timeout values.  I do see this message pop up sometimes after editing a profile that doesn't have the values mentioned.  Not sure but I believe this error is being handled in @jellypuno PR https://github.com/zowe/vscode-extension-for-zowe/pull/1100 I know I ran into it there as well. If this is correct @jellypuno let me know and I will approve this PR

2021-01-14 13:06 UTC, zdmullen commented
Merge this after Jelly's PR #1100!

2021-01-15 11:43 UTC, katelynienaber commented
@JillieBeanSim I think this issue was fixed in @jellypuno's PR, could you check it out again? I don't see it in mine.

2021-01-22 13:44 UTC, lauren-li submitted a review, later dismissed
This PR is looking good to me. All unit and expected integration tests are passing. I am able to create and edit profiles without specifying username, password, encoding, and/or timeout, and the yaml is created/updated without empty fields, which is really great. I do sometimes see the error that @JillieBeanSim mentioned in her [comment](https://github.com/zowe/vscode-extension-for-zowe/pull/1120#issuecomment-758738277) above, ... but I can also get it to happen in v1.11.1 the same way (but not reliably). We may want to look into it as a separate issue.

Another issue I encountered while testing, which I also see in 1.11.1 (and thus not a blocker for this PR) is that I get prompted for credentials immediately upon finishing creation or editing of a profile without username/password. I suppose this behavior has been around for a while, but somehow I only just now noticed it, and it feels unexpected since I am not trying to use the profile to access anything yet; I'm just udpating/creating it. Again, this could be investigated as a separate issue. I just wanted to mention it here so others are aware that it isn't a new behavior with this PR.

Thanks @katelynienaber for the fixes in this PR! It was such a pain to deal with empty profile fields when troubleshooting/testing other profile-related PRs, and I am happy to see that getting resolved.

2021-01-22 16:17 UTC, jellypuno commented
Maybe its just me but after I created my profile, I edited it and I encountered this error:

![image](https://user-images.githubusercontent.com/45042840/105516002-ab7fc900-5cd5-11eb-895a-9c2984a78de5.png)

This is my profile:
```
host: 192.86.32.250
port: 10443
rejectUnauthorized: false
```

2021-01-22 16:59 UTC, lauren-li commented
@JillieBeanSim and I have seen an issue in `master` branch, which is not a regression from this PR. However, the fact that this PR works like it's supposed to makes the existing issue much easier for users to encounter. It seems that when clicking a view's "RefreshAll" button, profiles without a user/password field are not refreshed:

![ze-refreshAll](https://user-images.githubusercontent.com/45975633/105519093-0a7a1980-5ca7-11eb-85a8-21f6a459adc6.gif)

In the gif above, the profiles `d`, `ncz`, and `tivNC` all had in common that they were missing user/password fields. Just to be sure, I also tested profiles that had user/password filled in, but lacked encoding/timeout fields (both with good hosts and bad hosts to test active vs inactive), and those profiles were also able to refresh fine.

I also get this message in the debug console when the issue occurs: `TypeError: Cannot read property 'ISession' of undefined at Object.refreshTree`.

We should be sure we can fix this issue in 1.12 before merging this PR in. Again, this PR does not seem to be causing the issue, but it just happens to expose the user to it very easily. (I am still very excited that we are getting rid of empty strings in the profile to mirror what Zowe CLI does, though.)

2021-01-25 08:37 UTC, katelynienaber commented
> Another issue I encountered while testing, which I also see in 1.11.1 (and thus not a blocker for this PR) is that I get prompted for credentials immediately upon finishing creation or editing of a profile without username/password.

@lauren-li I will look into this as part of PR #1150

2021-01-25 08:51 UTC, katelynienaber commented
@lauren-li I disagree that we should wait to merge this. I'm not convinced we can get another PR finished and reviewed twice by tomorrow. And therefore we would be delaying a bugfix for 3 issues affecting 5 profile fields until the next release, because it reveals 1 issue affecting 2 profile fields.

2021-01-25 10:23 UTC, jellypuno commented
Issues that needs to be addressed:

1. Cannot create a profile if I am using SCS
![image](https://user-images.githubusercontent.com/45042840/105692839-3c85b880-5eff-11eb-8854-c2d56ed53629.png)

2. This appears if I edit a newly created profile: 
![image](https://user-images.githubusercontent.com/45042840/105693014-7eaefa00-5eff-11eb-9979-63b4bf291f98.png)

    the yaml file was updated though.

    ![image](https://user-images.githubusercontent.com/45042840/105693090-9ab29b80-5eff-11eb-91fb-16f72aac96cb.png)

3. Similar to  @lauren-li comment, the status of the profile is not refreshing.

2021-01-25 11:17 UTC, jellypuno commented
For the SCS issue, I think there's something that we need to update in our own SCS. I am not sure what though. I'm hoping @t1m0thyj can help us.... 😊

2021-01-25 12:47 UTC, katelynienaber commented
> 1. Cannot create a profile if I am using SCS

Blargh SCS. This still needs fixing...

> 2. This appears if I edit a newly created profile:
>    ![image](https://user-images.githubusercontent.com/45042840/105693014-7eaefa00-5eff-11eb-9979-63b4bf291f98.png)

I've fixed this, just copied it out of the old base profiles PR

> 3. Similar to @lauren-li comment, the status of the profile is not refreshing.

@lauren-li @jellypuno I went ahead and fixed this here. Please please can we merge it like this it is such a small change, another PR for this would be overkill 8|

Original code:
`if (sessNode.getSession().ISession !== SessionProfile) {`
New fix:
`if (sessNode.getSession() && sessNode.getSession().ISession !== SessionProfile) {`
Now, it will not try to set the session at all, if the node doesn't already contain one. This is during refresh _only_. It will still update the session if you ex. edit the profile, or enter your creds at a prompt.

> 4. After step# 2 I clicked the magnifying glass and this error appears:
>    ![image](https://user-images.githubusercontent.com/45042840/105693490-157bb680-5f00-11eb-9675-9aec20171e22.png)
>    I've enabled validation and I am sure that the hostname is active. I expected that I will be prompted to enter my credentials

I am guessing you have created a profile with user/pass, and then are trying to immediately edit it and remove the user/pass...at least that's what I fixed. I just removed validation in the end of the `editSession` function. When you try to use the profile it will validate you as usual.

2021-01-25 13:22 UTC, jellypuno commented
@katelynienaber Once you push your commit, I'll test it again.

2021-01-25 13:25 UTC, katelynienaber commented
@jellypuno lol totally forgot to do this

2021-01-25 13:49 UTC, lauren-li commented
> @lauren-li I went ahead and fixed this here. Please please can we merge it like this it is such a small change, another PR for this would be overkill 8|

I think it's fine if it is fixed in this PR (which it now appears to be). My intention here wasn't to say that the fix _had_ to be in a separate PR, but that it could be if you didn't want to make any additional changes to this PR, since it was looking pretty good to me at the time I wrote my comment. However, since you've also made updates to address issues @jellypuno found, I will test the PR for those as well now. Thanks @katelynienaber for your hard work on this! I will let you know soon how my testing goes.

2021-01-25 14:44 UTC, t1m0thyj commented
> I think issue is [here](https://github.com/zowe/imperative/blob/741f24f7246028879317dbd9590b91d7efbdef39/packages/cmd/src/profiles/CliProfileManager.ts#L408)...imperative's save function is trying to delete the field from an existing profile, if you pass in a profile where the field is missing. Since we are making a new profile, the field doesn't exist and can't be deleted. The causeError I am getting is `Error: Unable to delete credentials. at KeytarCredentialManager.`

@katelynienaber This same issue used to happen in the SCS plugin. It was fixed by updating CredentialManager class to fail silently when it attempts to delete a non-existent secure field. This ensures that the field gets deleted if it exists, and eliminates the unwanted failure.

https://github.com/zowe/zowe-cli-scs-plugin/pull/7/files#diff-7fd952b958aa47583d7349b4404413e8918ccac03052333f1dfcb8990b5af5cfL105-L114

I'd suggest implementing the same fix for ZE's KeytarCredentialManager. If you agree it seems safe, you can remove the error being thrown in `deleteCredentialsHelper` 🙂 
https://github.com/zowe/vscode-extension-for-zowe/blob/f0f93e90e01eb0f725c9c630a2d406d61ae7b51d/packages/zowe-explorer/src/KeytarCredentialManager.ts#L73-L80

2021-01-25 15:02 UTC, katelynienaber commented
@t1m0thyj Thank you very much! Merging this fix now. I'm logging the error but it won't fail completely.

2021-01-25 21:52 UTC, lauren-li commented
Referencing @jellypuno's comment: https://github.com/zowe/vscode-extension-for-zowe/pull/1120#issuecomment-766713463

> 1. Cannot create a profile if I am using SCS

I don't see this issue when testing now.

> 2. This appears if I edit a newly created profile:

I don't see the error message @jellypuno posted; however, I do see this one when trying to edit a profile that has no username/password (whether newly-created or from a previous session):
<img width="452" alt="Screen Shot 2021-01-25 at 1 17 09 PM" src="https://user-images.githubusercontent.com/45975633/105768990-27bf1a00-5f2b-11eb-8069-7af2dff5953a.png">

> 3. Similar to @lauren-li comment, the status of the profile is not refreshing.

This appears to have been fixed!

> 4. After step# 2 I clicked the magnifying glass and this error appears:

- I still get these errors in MVS and Jobs when trying to run a search using a profile without credentials. (I also have validation enabled, and was expecting to be prompted for username/password.)
- In USS, when I try to run a search using a profile without credentials, I get a different error:
    <img width="452" alt="Screen Shot 2021-01-25 at 1 11 04 PM" src="https://user-images.githubusercontent.com/45975633/105769462-d6635a80-5f2b-11eb-9a11-20f81dbb4cae.png">

~

Some other odd behavior I saw that I wasn't able to produce on `master` branch:
- After deletion, profiles show up again in the dropdown list of available profiles when clicking the **+** button, even though their corresponding `yaml` file was deleted. (This doesn't happen 100% of the time, but I was able to recreate it fairly frequently, particularly for profiles without credentials.)
    ![ze-1120-deletep](https://user-images.githubusercontent.com/45975633/105770131-c9933680-5f2c-11eb-9a0a-7b0f179b7418.gif)

- Editing a profile (especially one without creds/encoding/timeout) causes it to be removed from the `sessions` list in the `settings.json` file (and therefore, the profile does not load automatically upon session restart). I also was not able to recreate this with 100% consistency, but I was still able to recreate it fairly frequently:
    ![ze-1120-editp](https://user-images.githubusercontent.com/45975633/105770372-1d9e1b00-5f2d-11eb-96d5-4e133372f66d.gif)

2021-01-26 10:31 UTC, katelynienaber commented
> I don't see the error message @jellypuno posted; however, I do see this one when trying to edit a profile that has no username/password (whether newly-created or from a previous session):

This error is present in master and is related to [this line](https://github.com/zowe/vscode-extension-for-zowe/blob/06a5fcc2bc087c80d00f4ee704616c078274f12b/packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts#L163). It isn't related to the original problem of empty fields being stored improperly and removing this line might cause adverse affects, so I won't fix it here. It doesn't stop you from editing the profile in any case.

> > 1. After step# 2 I clicked the magnifying glass and this error appears:
> 
> * I still get these errors in MVS and Jobs when trying to run a search using a profile without credentials. (I also have validation enabled, and was expecting to be prompted for username/password.)

I am inclined not to fix this one here. It's kind of a big deal XD And it's already going to happen in master if you have any invalid profile and no base profile, it's not caused by the changes in this PR. It occurs because we get to [this point](https://github.com/zowe/vscode-extension-for-zowe/blob/06a5fcc2bc087c80d00f4ee704616c078274f12b/packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts#L82) without ever having prompted for creds. In the original base profiles PR we did [this](https://github.com/zowe/vscode-extension-for-zowe/blob/f29a955740b6c4db74189f501cb994ae3011ebd2/src/api/ZoweExplorerZosmfApi.ts#L147), but to implement something like that would be a huge change that would require lots of testing.

> * In USS, when I try to run a search using a profile without credentials, I get a different error:

I rearranged the search function, so that it tries to retrieve the session from the node _after_ the node's profile is validated. **If you don't have user/pass on the profile, the error above will still occur.** But like I said that error is a biggie and should be dealt with separately. The workaround is to disable validation.

> * After deletion, profiles show up again in the dropdown list of available profiles when clicking the **+** button, even though their corresponding `yaml` file was deleted. (This doesn't happen 100% of the time, but I was able to recreate it fairly frequently, particularly for profiles without credentials.)

This should be fixed.

> * Editing a profile (especially one without creds/encoding/timeout) causes it to be removed from the `sessions` list in the `settings.json` file (and therefore, the profile does not load automatically upon session restart). I also was not able to recreate this with 100% consistency, but I was still able to recreate it fairly frequently:

This should also be fixed.

2021-01-26 12:05 UTC, jellypuno commented
@katelynienaber I am still having this error:

![image](https://user-images.githubusercontent.com/45042840/105842664-d4a2a100-5fd6-11eb-8215-13d2c923292e.png)


Steps to reproduce:
1. Create a new profile with invalid URL and without User and Password
2. Edit the said profile and enter the correct URL
3. Click the magnifying glass to search for a dataset

Note: My base profile contains host, port and ru. Same with my service profile. And the URL for both profiles are different

2021-01-26 12:10 UTC, jellypuno commented
I can create and edit profiles with token. thank you for that. I tried to submit a job and I encountered this error.

![image](https://user-images.githubusercontent.com/45042840/105843343-dc167a00-5fd7-11eb-8153-816970c86341.png)

2021-01-26 15:25 UTC, katelynienaber commented
@jellypuno Can you give it another shot please?

2021-01-26 15:28 UTC, lauren-li commented on packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
> +                this.mHistory.addSession(node.label);
Adding L172 ` this.mHistory.addSession(node.label);` seems to have fixed the issue where the profile was getting removed out of the `settings.json` file after editing, but I'm a little confused what lines 171-172 are meant to be doing now. It looks like L171 just removes the session from `settings.json` and then L172 just adds it back in and cancels L171 out. Could these two lines just be removed?

2021-01-28 13:41 UTC, jellypuno commented
Small issue, I think we can just filter this out and stop displaying it.

This appears when I right-click > Update Profile

![image](https://user-images.githubusercontent.com/45042840/106146304-cf7c5800-6176-11eb-8acb-f8a8ef061796.png)

2021-01-28 14:02 UTC, jellypuno commented
Error when I tried to add a newly created profile in USS favorites:

![image](https://user-images.githubusercontent.com/45042840/106148843-d5276d00-6179-11eb-9daa-7c5002bb79f6.png)

2021-01-28 17:49 UTC, katelynienaber commented
@jellypuno Fixed this...there is still the "profile inactive" error popping up, but the profile is added to favorites. I think this inactive error should be dealt with in another PR, because it occurs all over ZE, not just in profiles operations.

2021-01-28 17:54 UTC, lauren-li commented
@katelynienaber What is the expected result if the user has made profile ABC without credentials, does not have a base profile, and uses profile ABC to run a search? I get the set of errors below. I was thinking we should be prompting users for username/password, but I don't get a chance to do that with my new profile:

<img width="451" alt="Screen Shot 2021-01-28 at 12 49 18 PM" src="https://user-images.githubusercontent.com/45975633/106178181-72c57100-6167-11eb-859f-bbd7235b3186.png">

2021-01-28 18:06 UTC, katelynienaber commented
@lauren-li If you can turn off validation for the profile and get a prompt thereafter...see my post above XD Basically the flow is messed up for validation and it's too big of an unrelated issue to be addressed here.

If you turn off validation and it still won't prompt, let me know, I will try again.

> I am inclined not to fix this one here. It's kind of a big deal XD And it's already going to happen in master if you have any invalid profile and no base profile, it's not caused by the changes in this PR. It occurs because we get to this point without ever having prompted for creds. In the original base profiles PR we did this, but to implement something like that would be a huge change that would require lots of testing.

2021-01-28 18:13 UTC, JillieBeanSim commented
@katelynienaber @jellypuno @lauren-li if the user has to do a bunch of work arounds to have this PR in and their profiles to show up and work then I personally don't think this should go out in this release.  I agree the inactive error should be dealt with in another PR but I also believe that this PR and the inactive one will need to go out together possibly as bug fixes in 1.12.1.  This is just my opinion so we don't break users and have to point them to workarounds like disabling validation or requiring them to have a base profile.

2021-01-28 18:20 UTC, lauren-li commented
@katelynienaber I'm inclined to agree with @JillieBeanSim on this. This PR is in pretty good shape, I really like it, and like you said, fixing the root cause of the error prompts is a bigger issue. But introducing this feature without addressing those prompts has the potential to degrade the user experience, since they would now be getting errors for something they were able to do without any problems before.

2021-01-28 18:24 UTC, JillieBeanSim commented
I may be able to even pitch in with the inactive error/prompting for creds if the field is missing PR as to have these ready for 1.12.1, I was fiddling with it a couple of weeks ago before I jumped in with the filter icon PR

2021-01-28 18:31 UTC, katelynienaber commented
@lauren-li @JillieBeanSim It's fine with me if you want to wait on this one, it wasn't promised in the PI goals :D We should bring it up with @zdmullen and @jellypuno as well.

2021-02-08 13:35 UTC, JillieBeanSim approved these changes
This PR works great now with https://github.com/zowe/vscode-extension-for-zowe/pull/1178 added in.  I don't see any of the issues we were seeing before.  Thanks @katelynienaber for doing this work.  All expected tests and checks are passing

2021-02-08 15:17 UTC, lauren-li approved these changes
This looks good to me now! All unit and expected integration tests are passing. Omitting credentials when creating and updating a profile in Zowe Explorer now omits the respective fields instead of creating empty strings. With the merging-in of PR #1178, this works much more seamlessly than before (i.e. no new "error" pop-ups). This PR also appears to be "backwards compatible" with the existing credential-less profiles, in that those profiles are still able to be used, and updating them with empty credentials will just completely remove the blank `user` and `password` fields.

Thanks @katelynienaber for your hard work on this PR!

2021-02-08 15:23 UTC, merged