zFTP ReadMe and Changeloe update
zowe/vscode-extension-for-zowe pull request #1235
Opened 2021-03-11 13:02 UTC by IgorCATech

## Proposed changes

Update the Readme doc by adding the What's New section. For the 1.13 release, we are adding a number of data set functionalities. Also, the Changelog will be updated accrodingly.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-03-11 15:28 UTC, IgorCATech commented
Just a reminder for myself: Update Line 74 in the landing ReadMe doc by adding "interact with z/OS USS and MVS" once #1199 is merged

2021-03-11 16:52 UTC, crawr commented on packages/zowe-explorer-ftp-extension/README.md
> +- Show Data Set Attribute — Supported
Perhaps we can remove the `- Supported` tag for each of them since we only list supported ones anyway

2021-03-12 11:03 UTC, lauren-li requested changes
This is looking good to me! I only have some small, quick fixes to suggest.

Thank you @IgorCATech for keeping this up-to-date!

2021-03-12 11:09 UTC, IgorCATech commented on packages/zowe-explorer-ftp-extension/README.md
> +3. After the install, when Zowe Explorer now activates it will show a VS Code info message "Zowe Explorer was modified for FTP support." to confirm that the FTP extension is available within Zowe Exp
oh yeah, I know about this. At some point, this way might confuse a writer if there are long procedures, so I'll just stick to numbering :) no big deal hehe

2021-03-12 14:46 UTC, lauren-li approved these changes
Thank you @IgorCATech for the revisions! This PR looks good to me now!

2021-03-15 10:36 UTC, jellypuno approved these changes

2021-03-15 10:36 UTC, merged