Refresh USS Folder Contents
zowe/vscode-extension-for-zowe pull request #1369
Opened 2021-06-21 17:30 UTC by rudyflores

## Proposed changes

Prior to this PR the user was unable to refresh file names in a USS directory without having to collapse the tree, this could be unintuitive for the user since the tree would collapse and would have to expand their directories after every refresh is performed. With this new change the user will be able to refresh directory file names without the tree collapsing and provide a better experience for the user.

## Release Notes

Milestone: 1.17
Changelog: Refresh for USS directory file names without the tree collapsing

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

2021-06-22 17:48 UTC, JillieBeanSim requested changes
@rudyflores functionality works great! The only thing I see that will need fixing is the broken unit tests which just need the command count updated like done in the DS Refresh PR
![image](https://user-images.githubusercontent.com/49491949/122973943-c5ded100-d35f-11eb-8ff5-5f002db13f01.png)

2021-06-23 14:53 UTC, lauren-li requested changes
This PR is off to a good start! Once you address my comment below in addition to @JillieBeanSim's earlier request to update the unit test, I will review the PR again. Thanks @rudyflores!

2021-06-23 14:53 UTC, lauren-li commented on packages/zowe-explorer/package.json
> +        },
@rudyflores Please remove this block (lines 711-715), as `zowe.uss.refreshUSS` is already declared with the same `when` clause further down (lines 736-740). It is causing the refresh ("Pull from mainframe") command to appear twice for files:

<img width="248" alt="Screen Shot 2021-06-23 at 10 47 35 AM" src="https://user-images.githubusercontent.com/45975633/123118334-8a500f80-d410-11eb-8ab7-839fee48702b.png">

2021-06-24 10:03 UTC, lauren-li submitted a review, later dismissed
This looks good to me now. All unit and expected integration tests are passing. The new command is located in the correct context menu group, and functions as expected. Thanks @rudyflores for addressing my comments!

2021-06-24 11:53 UTC, JillieBeanSim reviewed
@rudyflores this LGTM, thanks for addressing the comments and for your work on this.  

I am wondering if we should also have this option at the session node to refresh the search if something was done at top level.  For example:
do a USS filter search for `/u/userid/directory` then something in that directory changes on host side, like a new file or a file was deleted/renamed, should the option to `Refresh USS Directory` appear in right-click menu here as well?  @lauren-li 
![image](https://user-images.githubusercontent.com/49491949/123258325-410bc880-d4c1-11eb-9366-cac343ede58f.png)

2021-06-24 20:42 UTC, JillieBeanSim approved these changes
LGTM! Thanks @rudyflores this is an awesome feature.

2021-06-24 23:43 UTC, phaumer commented
Very nice. I cannot believe how easy that was :-) 

I would change the name though: as we have "Create Directory" directly below the naming should be consistent and just be  "Refresh Directory" without the USS; the entire view is USS.

![2021-06-24_16-39-07](https://user-images.githubusercontent.com/4391934/123345484-0464bf00-d50b-11eb-8980-69477d9147a0.png)

2021-06-25 12:53 UTC, lauren-li approved these changes
This PR looks good to me. All unit and expected integration tests are still passing, and the added functionality to refresh the USS directory from the profile level is working well.

I am approving this PR, but I also think @phaumer made a good point that the command titles will be more consistent if we use "Refresh Directory" instead of "Refresh USS Directory". I would be happy to re-approve the PR with this change being made.

Thanks @rudyflores for your hard work on this PR!

2021-06-28 14:03 UTC, lauren-li approved these changes
This PR looks good to me. Thanks @rudyflores for the command label update!

2021-06-28 14:09 UTC, JillieBeanSim approved these changes
LGTM, thanks @rudyflores

2021-06-29 13:13 UTC, merged