Documentation for imperative logger for extenders
zowe/vscode-extension-for-zowe pull request #1467
Opened 2021-08-27 09:07 UTC by katelynienaber

Signed-off-by: Katelyn Nienaber <katelyn.nienaber@broadcom.com>

## Proposed changes

Updates to Error Handling.md, advising extenders to use the new API logging functions.

## Release Notes

Milestone: 2.0
Changelog: Updates to Error Handling.md, advising extenders to use the new API logging functions.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

2021-08-31 12:32 UTC, JillieBeanSim requested changes
I was wondering about the number value that was passed for severity and how the user would know which to pass so I wanted to look here at the docs for examples/explanation of that.  In these example you have `MessageSeverityEnum.TRACE` or ERROR.  Would it make more sense to show the extender here a copy of the `MessageSeverityEnum` with appropriate values so the extender knows what values, 0-5, are available ?

2021-09-01 07:00 UTC, katelynienaber commented
@JillieBeanSim Good point! I've added this to the docs as well.

2021-09-01 09:54 UTC, jellypuno approved these changes

2021-09-01 13:20 UTC, JillieBeanSim approved these changes
Awesome! Thanks @katelynienaber LGTM

2021-09-01 13:28 UTC, merged