[Issue #845] Do not show undefined spool files for a job
zowe/vscode-extension-for-zowe pull request #1584
Opened 2021-11-19 16:50 UTC by roman-kupriyanov

## Proposed changes

Resolves an issue #845 by skipping all the objects which are returned from `GetSpoolFiles` API call and do not correspond to the proper `zowe.IJobFile` type. As a result there will be no more `undefined:undefined(undefined)` items in the spool files tree.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

2021-11-23 13:16 UTC, jellypuno requested changes
As per discussion, please add the text " There are no JES spool messages to display" when I click on the arrow. Thank you and well done on your first PR! 🎉

2021-11-23 13:43 UTC, roman-kupriyanov commented
> As per discussion, please add the text " There are no JES spool messages to display" when I click on the arrow. Thank you and well done on your first PR! 🎉

Thank you, Jelly! 😊 

That would be a great addition for the UX in general. Nice idea! Will add it..

2021-11-24 13:15 UTC, uzust01 commented
Looks good!

2021-11-25 11:26 UTC, nickImbirev commented
I'm not sure, that the proposed behaviour will solve the problem. In the end, the user will still try to submit the job with the '&' in the job name (in the beginning) and they will not be able to see any spool files for it. I would consider this as a bug :(

But I do understand, that there is additional contribution required from the SDK authors. Maybe we can at least submit a GH issue for them? And make additional issue in our repo to fix the `?`, `&` and other problematic symbols in our URI serialisation process?

2021-11-25 11:54 UTC, jellypuno commented
`And make additional issue in our repo to fix the ?, & and other problematic symbols in our URI serialisation process`

@nickImbirev I do not understand what do you mean by this. If mainframe is accepting `?`, `&` in their JCLs, we are going to do accept that as well.

I agree that we should open an issue against the SDK or the CLI team because if you fire the APIs the records are available. I am not sure why they are giving us an empty response.

![image](https://user-images.githubusercontent.com/45042840/143437003-f0fe816f-0dcc-4ccc-9513-317fe24dc482.png)

FIles:
![image](https://user-images.githubusercontent.com/45042840/143437049-3913770b-fb55-46d5-a6e9-dac6469f25e1.png)

Records:
![image](https://user-images.githubusercontent.com/45042840/143437095-e76a3ed7-b3e6-4a6f-bba3-23dcbcf5e6ff.png)

2021-11-25 12:01 UTC, jellypuno commented
@roman-kupriyanov I am going to accept this as a solution for the issue but I agree with @nickImbirev that we should open a GH issue about the response that we are getting from the SDK. As seen in the screenshots, The z/OSMF response contains the records that we need. We need investigate why the SDK is not giving that to us. Can you please open an issue in the zowe/cli repo?

2021-11-25 12:36 UTC, roman-kupriyanov commented
> Can you please open an issue in the zowe/cli repo?

Yes, sure, I was about to propose the same today.

A root cause for that is in the z/OSMF request URL, where `&,?` are the special symbols to organize the query part of that URL and it is constructed inside `@zowe/cli` API's for `GetSpoolFiles` call, out of our control on on the ZE level at the moment. From z/OSMF perspective though, alternatively, you can use **a Job correlator** value to do the same call and it does not contain any special characters, which breaks URL. Also, it is specified in those response fields `files-url` and `records-url`, which is why those links are working perfectly. `@zowe/cli` does not provide "the Job correlator way" of making calls to z/OSMF, except using `jobname/jobid`, which will be broken each time they contain `&,?` or any other special symbols:
https://github.com/zowe/zowe-cli/blob/0cc2ed46de784876172d79d16c1548e2b3fb23c1/packages/zosjobs/src/GetJobs.ts#L253

In sum, I assume, an issue about adding the alternative way of calls for `@zowe/cli` is what may help us with this issue in general. So I will create it 😉

2021-11-25 12:59 UTC, jellypuno commented
@roman-kupriyanov That is a good point. Yes. suggest that alternative way 👍

2021-11-25 14:19 UTC, merged