Bug/refresh job/status
zowe/vscode-extension-for-zowe pull request #1936
Opened 2022-09-09 16:33 UTC by KutluOzel-b

## Proposed changes

Fix refresh job & spool file pull from mainframe doesn't update job status by refreshing parent node.

## Release Notes

Milestone:
https://github.com/zowe/vscode-extension-for-zowe/issues/1857

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

The Bug is solved by refreshing parent node method which leads to refreshing unnecessary nodes as well. Since we are populating nodes into belonging trees in a singular way this maybe not the best option but good for consistency.

2022-09-14 14:51 UTC, JillieBeanSim requested changes
Functionality LGTM, thanks @KutluOzel-b.  Would you mind adding the bugfix description to the ZE CHANGELOG please.

2022-09-15 12:17 UTC, zFernand0 commented on packages/zowe-explorer/CHANGELOG.md
> +## `2.3.1`
it'd be nice if we used `## TBD Release` or something like that.
That way we don't have to dictate which version we believe this PR will be published in.
For example, there may be other PRs already in (or in route to) `main` that introduce enhancements.

2022-09-15 12:59 UTC, zFernand0 approved these changes

2022-09-15 13:11 UTC, JillieBeanSim approved these changes

2022-09-15 13:12 UTC, merged