Enhance UX for managing credentials
zowe/vscode-extension-for-zowe pull request #2445
Opened 2023-09-06 21:07 UTC by t1m0thyj

## Proposed changes

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

2023-09-14 20:51 UTC, traeok submitted a review, later dismissed
LGTM, thanks @t1m0thyj 😁

2023-09-15 20:16 UTC, JillieBeanSim commented on packages/zowe-explorer/CHANGELOG.md
> +- Replaced multiple options for updating credentials with a single "Manage Credentials" option that prompts for preferred authentication type. [#2263](https://github.com/zowe/vscode-extension-for-zow
should move CHANGELOG item under TBD

2023-09-15 20:45 UTC, JillieBeanSim requested changes
this is looking great @t1m0thyj!!
I was wondering if the logout option should be a radio button too? maybe not since the others are showing what is in use. Should we use a separator line for logout then similar to add/create profile?
<img width="335" alt="Screen Shot 2023-09-15 at 4 44 22 PM" src="https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/1e33639d-6b3b-4010-a227-8e0f0dd49eea">



I also notice that the quickpick didn't close after choosing the logout option, I have to escape it.
<img width="834" alt="Screen Shot 2023-09-15 at 4 38 30 PM" src="https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/34f360a4-c408-4ad2-8066-0355906220da">

2023-09-18 15:22 UTC, JillieBeanSim approved these changes
Thanks for pushing the latest updates, everything works great! Thanks @t1m0thyj for this enhancement

2023-09-18 15:56 UTC, rudyflores requested changes
When performing a token auth login, seems to be working well, I do have a concern in terms of the UI/UX for logging out in this change, should we show instead just a "logout" button or show the option for logout as a radio button too? i'm curious why it has a different UI for the logout.

Another thing I wanted to mention is that when clicking "logout" the pop up window with the option doesn't close but remains open, but the bottom right show that logout was done successfully, my feedback on this is I felt like maybe there is no feedback when clicking on the button that will tell the user that they logged out unless they look at the bottom right, I think maybe closing the pop up selection menu will help with this!

<img width="602" alt="Screenshot 2023-09-18 at 11 53 03 AM" src="https://github.com/zowe/vscode-extension-for-zowe/assets/68666202/3b7bdb44-4126-46ad-8eb1-f364292eee7f">

2023-09-18 16:03 UTC, rudyflores commented
One more thing @t1m0thyj 

if you perform the following on a z/OSMF or extender profile:
1. Log in with token auth
2. click manage credentials and choose basic auth
3. type in credentials for basic auth

This causes now the profile to be using both basic and token auth which now doesn't allow the user to logout unless the secure array properties with `user` and `password` are removed, I think we may not want to mix credential management types here but may be something we can discuss as well.

2023-09-19 13:36 UTC, t1m0thyj commented
@rudyflores Thanks for the feedback! 😍 

> When performing a token auth login, seems to be working well, I do have a concern in terms of the UI/UX for logging out in this change, should we show instead just a "logout" button or show the option for logout as a radio button too? i'm curious why it has a different UI for the logout.

The radio buttons are for authentication options (User and Password, Authentication Token, and in the future Certificate File). Since logout is an action separate from these, I don't think it should be a radio button. I agree a "logout" button would be nice but unfortunately the UI options provided by VS Code for quickpicks are limited so we can't show a button with text on its own row. I've mocked up some alternative ideas:
1. Logout icon shown on the right of the quickpick - this is the only style of button they support. The button can show a tooltip when hovered, but I'm not sure if its obvious enough for users to easily find the "logout" option.
    <img width="768" alt="image" src="https://github.com/zowe/vscode-extension-for-zowe/assets/22344007/e2d8c488-12ae-492b-b8ed-d6a590fa352f">
2. Adding an icon to the existing "logout" option - this is a small change but I think it looks better.
    <img width="607" alt="image" src="https://github.com/zowe/vscode-extension-for-zowe/assets/22344007/0fc51f50-8edc-49fb-be12-05f98320290d">

> Another thing I wanted to mention is that when clicking "logout" the pop up window with the option doesn't close but remains open, but the bottom right show that logout was done successfully, my feedback on this is I felt like maybe there is no feedback when clicking on the button that will tell the user that they logged out unless they look at the bottom right, I think maybe closing the pop up selection menu will help with this!

Agree that the popup should close after logout, did you test with the latest commit? There was an issue with the popup not being closed that Billie pointed out which should be fixed in https://github.com/zowe/vscode-extension-for-zowe/pull/2445/commits/5a6fc3abdedf6d3503469b40820fcd00db82fefc

2023-09-21 14:52 UTC, JillieBeanSim commented
Hey @t1m0thyj due to concerns with the authentication methods and pre-existing issues with offering basic auth info gathering while token auth in place and other issues I have started work on a [POC](https://github.com/zowe/vscode-extension-for-zowe/pull/2472) for profile management based off of these ideas, keep in mind this isn't complete yet.  We can continue discussions on how we would like to proceed

2023-09-26 15:00 UTC, closed without merging