Refactor of webview code
zowe/vscode-extension-for-zowe pull request #2489
Opened 2023-09-28 20:16 UTC by rudyflores

## Proposed changes

Refactor of existing Webview code to be easily extensible, this also integrates a watcher that will hot reload your changes on your webview to the debugger so you can see your changes just by saving!

To add new views in the future just:

1. add new folder with webview name to `zowe-explorer/src/webviews/src`.
2. add the following components: `index.html`, `app.tsx`, `index.tsx`, `types.ts` (optional)

And that's it! 

## Release Notes

Milestone: 2.12.0

Changelog: Added new method of creating webviews on Zowe Explorer

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

2023-09-29 17:42 UTC, rudyflores commented
FYI: the code smell is from existing `App.tsx` work from @traeok 's work on editing attributes, this can be perhaps be addressed in a separate PR since the code in that file could be restructures into components in the future.

2023-09-29 19:59 UTC, awharn commented on packages/zowe-explorer-api/src/vscode/ui/WebView.ts
> +     * @param webviewName The directory name (relative to the "webviews" folder in the extension root) with a valid entrypoint (see above).
The description for this parameter does not match the parameter name

2023-10-02 14:26 UTC, traeok approved these changes
LGTM, thanks @rudyflores!

2023-10-02 14:38 UTC, awharn submitted a review, later dismissed

2023-10-02 14:49 UTC, traeok requested changes
Sorry for the sudden change in review @rudyflores. I was under the impression that the dev host was showing the latest changes, but the `watch` script seems to be failing for me:

![image](https://github.com/zowe/vscode-extension-for-zowe/assets/86500639/6bb735f8-4569-4227-aff0-8223b5cb1b50)

2023-10-02 14:55 UTC, zFernand0 submitted a review, later dismissed

2023-10-02 16:27 UTC, rudyflores commented
All fixed now @traeok good catch on the windows end of things for concurrently!

2023-10-02 16:41 UTC, traeok approved these changes

2023-10-02 17:47 UTC, zFernand0 approved these changes

2023-10-02 17:48 UTC, merged