Add option for hiding profile from all trees
zowe/vscode-extension-for-zowe pull request #2566
Opened 2023-11-10 19:24 UTC by rudyflores

## Proposed changes

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

2023-11-13 15:48 UTC, zFernand0 requested changes
The prompt and everything around the functionality LGTM! 😋 

I did notice that some of the old options came back in the USS context menu.
![image](https://github.com/zowe/vscode-extension-for-zowe/assets/37381190/f50076fa-d514-4dd1-a96c-1013c6a6bfd6)
This doesn't happen (for me) on 2.12.1.

Also, the Edit history is above the Manage profile on the Jobs (but this also happens on the main branch)

2023-11-13 16:05 UTC, rudyflores commented
> The prompt and everything around the functionality LGTM! 😋
> 
> I did notice that some of the old options came back in the USS context menu. ![image](https://user-images.githubusercontent.com/37381190/282512584-f50076fa-d514-4dd1-a96c-1013c6a6bfd6.png) This doesn't happen (for me) on 2.12.1.
> 
> Also, the Edit history is above the Manage profile on the Jobs (but this also happens on the main branch)

Hey Fernando! That issue should be resolved once this PR is merged https://github.com/zowe/vscode-extension-for-zowe/pull/2559

As for the menu order issue you mentioned that is not relevant to this change, but could create an issue for that an I can address that separately :)

2023-11-13 17:06 UTC, traeok submitted a review, later dismissed
LGTM - left a comment about a type cast, but the current logic won't affect the behavior 😅 
Thanks @rudyflores!

2023-11-13 17:06 UTC, traeok commented on packages/zowe-explorer/src/uss/init.ts
> +    return ussFileProvider as USSTree;
We can avoid this type cast by removing the type annotation or changing the annotation to `USSTree` on line 27.

2023-11-13 17:55 UTC, zFernand0 reviewed
LGTM! 😋 
I'll wait for the PR below before approving
- #2559

2023-11-13 18:21 UTC, traeok approved these changes
Thanks again for removing the cast and fixing the errors from the type change 😁

2023-11-14 12:45 UTC, JillieBeanSim reviewed
Hey @rudyflores this is looking great! I do have one question.
If the profile name is only in a single tree, is there a way for us to know this and react appropriately?  I tested this situation and had a profile name in a single tree and was still prompted to choose.  I didn't get any errors or anything from choosing all trees, but wonder if we can tell beforehand, and if only in a single tree just remove it instead of the prompt that doesn't really make sense if only in one tree.

2023-11-14 14:54 UTC, rudyflores commented
> Hey @rudyflores this is looking great! I do have one question. If the profile name is only in a single tree, is there a way for us to know this and react appropriately? I tested this situation and had a profile name in a single tree and was still prompted to choose. I didn't get any errors or anything from choosing all trees, but wonder if we can tell beforehand, and if only in a single tree just remove it instead of the prompt that doesn't really make sense if only in one tree.

Perhaps we can cycle through each tree and see if the session exists in atleast another tree, if only in the current tree we can just remove the current one?

2023-11-16 14:08 UTC, traeok approved these changes

2023-11-16 16:07 UTC, zFernand0 approved these changes
I was testing right before the meeting, 
I just forgot to approve :cry:

LGTM! :yum:

2023-11-16 16:21 UTC, merged