Removal of Documentation related to Theia
zowe/vscode-extension-for-zowe pull request #2744
Opened 2024-02-26 11:09 UTC by likhithanimma1

## Proposed changes

Address #2726 
Removal of Theia support in documentation and others.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

2024-02-26 15:09 UTC, traeok requested changes

2024-02-26 15:09 UTC, traeok commented on packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
> +    public async getProfileInfo(): Promise<zowe.imperative.ProfileInfo> {
Since this class is exposed in ZE API, we should have a changelog entry for this breaking change.

2024-02-27 14:53 UTC, zFernand0 submitted a review, later dismissed
LGTM! 😋 
Hey @anaxceron, Do we need an equivalent change for Zowe Docs?

2024-02-27 15:47 UTC, t1m0thyj submitted a review, later dismissed
LGTM, thanks @likhithanimma1!

2024-02-27 15:50 UTC, traeok submitted a review, later dismissed
LGTM, thanks @likhithanimma1! 😁

2024-02-27 16:08 UTC, anaxceron approved these changes
Looks good. Had one comment about the changelog.

2024-02-27 18:54 UTC, zFernand0 approved these changes

2024-02-27 18:54 UTC, merged